version: '3.6'

services:
  backend:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
      - SECRET_KEY=tf$utx+@t(tj&c04i7wva%70ol-uozr3!8$ap=1v_(5vlksxsi
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=postgres://postgres:postgres@db:5432/noverde_challenge
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=noverde_challenge

volumes:
  postgres_data:
networks:
  backend:
